name: validation

on:

  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:

  build:
  
    runs-on: ubuntu-latest
    container: slacgismo/gridlabd:develop
    
    steps:
    
      - uses: actions/checkout@v2
        
      - name: update 
        run: /usr/local/opt/gridlabd/current/bin/python3 -m pip install -r requirements.txt
      
      - name: validate 
        run: sh ./autotest.sh
        
      - name: artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: autotest-errors
          path: autotest-errors.tar.gz
